"""The recurring Japan calendar, computed rather than remembered.

Upcoming is generated by the model from a list of dates in the prompt, which
goes stale. Told to produce events from an exhausted list a model invents
them; told not to invent, it produces none. Korea shipped both failures before
this module existed there.

Recurring dates do not need a model at all. Constitution Day is 3 May every
year. The Hiroshima anniversary is 6 August. These are arithmetic, so they are
computed here and merged with whatever dated events the model found in today's
articles. A date from this file cannot be wrong about the year, because it is
derived from today's date rather than recalled.

What is deliberately NOT here: anything that moves. Diet sessions, BOJ rate
decisions, summits, election dates and exercise windows shift, so they must
come from an article that states them. A fixed anniversary is safe to compute;
a scheduled event is not.
"""
from __future__ import annotations

from datetime import date, timedelta

# (month, day, headline, detail). Fixed observances only — nothing that can be
# rescheduled. Keep this list short and certain; it is the floor, not the
# whole calendar.
RECURRING: list[tuple[int, int, str, str]] = [
    (1, 1, "New Year (正月)",
     "National holiday. The PM's new-year press conference sets the year's line."),
    (2, 11, "National Foundation Day (建国記念の日)", "National holiday."),
    (2, 23, "The Emperor's Birthday (天皇誕生日)", "National holiday."),
    (3, 11, "Great East Japan Earthquake anniversary",
     "2011 earthquake, tsunami and the Fukushima Daiichi accident. Energy "
     "policy debate typically clusters here."),
    (4, 29, "Showa Day (昭和の日)", "Opens Golden Week."),
    (5, 3, "Constitution Memorial Day (憲法記念日)",
     "The 1947 constitution took effect. Article 9 revision arguments are made "
     "on this day by both sides."),
    (6, 23, "Okinawa Memorial Day (慰霊の日)",
     "End of the Battle of Okinawa, 1945. Base-hosting politics are at their "
     "most visible."),
    (8, 6, "Hiroshima Peace Memorial Ceremony",
     "1945 atomic bombing. The Peace Declaration often addresses the TPNW and "
     "extended deterrence."),
    (8, 9, "Nagasaki Peace Memorial Ceremony", "1945 atomic bombing."),
    (8, 15, "End-of-war anniversary (終戦記念日)",
     "The PM's statement and any cabinet visit to Yasukuni are read closely in "
     "Seoul and Beijing."),
    (9, 1, "Great Kanto Earthquake anniversary / Disaster Prevention Day",
     "1923. National disaster drills."),
    (11, 3, "Culture Day (文化の日)",
     "The 1946 constitution was promulgated on this date."),
    (12, 8, "Pearl Harbor anniversary", "1941. Alliance commentary clusters here."),
]

_MONTHS = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


def _next_occurrence(month: int, day: int, today: date) -> date:
    """The next time this month/day falls, today included."""
    for year in (today.year, today.year + 1):
        try:
            candidate = date(year, month, day)
        except ValueError:              # 29 February in a common year
            continue
        if candidate >= today:
            return candidate
    return date(today.year + 1, month, day)


def upcoming(today: date | None = None, days: int = 30) -> list[dict]:
    """Recurring observances falling within the window, soonest first.

    Shaped like the model's own calendar_watch items so the renderer needs no
    special case.
    """
    today = today or date.today()
    horizon = today + timedelta(days=days)
    out = []
    for month, day, headline, detail in RECURRING:
        when = _next_occurrence(month, day, today)
        if today <= when <= horizon:
            out.append({
                "month": _MONTHS[when.month - 1],
                "day": when.day,
                "headline": headline,
                "detail": detail,
                "_source": "recurring",
                "_date": when.isoformat(),
            })
    return sorted(out, key=lambda item: item["_date"])


# 60 days, not Korea's 30. Korea has thirteen fixed observances spread evenly
# enough that a month always contains one. This calendar has long gaps — the
# stretch from early September to early November holds none — and a horizon
# that returns nothing for two months defeats the point of computing them.
_HORIZON_DAYS = 60


def merge(model_items: list | None, today: date | None = None,
          days: int = _HORIZON_DAYS, limit: int = 5) -> list[dict]:
    """Combine the model's dated events with the computed observances.

    The model's items come first: an event it found in today's reporting is
    more informative than an anniversary anyone could look up. Recurring dates
    fill the remaining slots so the section is never empty, and are skipped
    when the model already reported the same day.
    """
    today = today or date.today()
    merged: list[dict] = []
    seen_days: set[tuple[str, int]] = set()

    for item in (model_items or []):
        if not isinstance(item, dict):
            continue
        headline = str(item.get("headline") or "").strip()
        if not headline:
            continue
        merged.append(item)
        month = str(item.get("month") or "").strip()[:3]
        try:
            seen_days.add((month, int(item.get("day"))))
        except (TypeError, ValueError):
            pass

    for item in upcoming(today, days):
        if len(merged) >= limit:
            break
        if (item["month"], item["day"]) in seen_days:
            continue
        merged.append(item)

    # A calendar reads in date order. Items the model dated with a month and
    # day sort by that; anything it left undated keeps its position at the end
    # rather than being dropped.
    def _key(item: dict) -> tuple:
        if item.get("_date"):
            return (0, item["_date"])
        month = str(item.get("month") or "").strip()[:3].title()
        try:
            m = _MONTHS.index(month) + 1
            d = int(item.get("day"))
        except (ValueError, TypeError):
            return (1, "")
        return (0, _next_occurrence(m, d, today).isoformat())

    return sorted(merged, key=_key)[:limit]
